run:
  # exit code when at least one issue was found, default is 1
  issues-exit-code: 0

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - unparam

severity:
  default-severity: warning
  rules:
    - linters:
      - unparam
      severity: info
