linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - unparam

severity:
  default-severity: warning
  rules:
    - linters:
      - unparam
      severity: info
